dist: trusty
language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew build --stacktrace

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - "$HOME/.gradle"
