package com.ryanharter.auto.value.moshi;

import com.google.auto.value.processor.AutoValueProcessor;
import com.google.common.collect.ImmutableSet;
import com.google.testing.compile.JavaFileObjects;
import org.junit.Before;
import org.junit.Test;

import javax.tools.JavaFileObject;
import java.util.Arrays;

import static com.google.common.truth.Truth.assertAbout;
import static com.google.testing.compile.JavaSourceSubjectFactory.javaSource;
import static com.google.testing.compile.JavaSourcesSubjectFactory.javaSources;

public final class AutoValueMoshiExtensionTest {
  private JavaFileObject serializedName;
  private JavaFileObject nullable;

  @Before public void setup() {
    serializedName =
        JavaFileObjects.forSourceString("com.ryanharter.auto.value.moshi.SerializedName", ""
        + "package com.ryanharter.auto.value.moshi;\n"
        + "import java.lang.annotation.Retention;\n"
        + "import java.lang.annotation.Target;\n"
        + "import static java.lang.annotation.ElementType.METHOD;\n"
        + "import static java.lang.annotation.ElementType.PARAMETER;\n"
        + "import static java.lang.annotation.ElementType.FIELD;\n"
        + "import static java.lang.annotation.RetentionPolicy.SOURCE;\n"
        + "@Retention(SOURCE)\n"
        + "@Target({METHOD, PARAMETER, FIELD})\n"
        + "public @interface SerializedName {\n"
        + "  String value();\n"
        + "}");

    nullable = JavaFileObjects.forSourceString("com.ryanharter.auto.value.moshi.Nullable", ""
        + "package com.ryanharter.auto.value.moshi;\n"
        + "import java.lang.annotation.Retention;\n"
        + "import java.lang.annotation.Target;\n"
        + "import static java.lang.annotation.ElementType.METHOD;\n"
        + "import static java.lang.annotation.ElementType.PARAMETER;\n"
        + "import static java.lang.annotation.ElementType.FIELD;\n"
        + "import static java.lang.annotation.RetentionPolicy.SOURCE;\n"
        + "@Retention(SOURCE)\n"
        + "@Target({METHOD, PARAMETER, FIELD})\n"
        + "public @interface Nullable {\n"
        + "}");
  }

  @Test public void simple() {
    // Note that the jsonAdapter() method can be package-private
    JavaFileObject source = JavaFileObjects.forSourceString("test.Test", ""
        + "package test;\n"
        + "import com.squareup.moshi.Json;\n"
        + "import com.ryanharter.auto.value.moshi.SerializedName;\n"
        + "import com.ryanharter.auto.value.moshi.Nullable;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.util.Map;\n"
        + "import java.util.Set;\n"
        + "@AutoValue abstract class Test {\n"
        + "  public static JsonAdapter<Test> jsonAdapter(Moshi moshi) {\n"
        + "    return new AutoValue_Test.MoshiJsonAdapter(moshi);\n"
        + "  }\n"
        // Reference type
        + "public abstract String a();\n"
        // Array type
        + "public abstract int[] b();\n"
        // Primitive type
        + "public abstract int c();\n"
        // SerializedName // TODO uncomment this once the target is updated in Moshi
        + "/*@Json(name=\"_D\")*/ public abstract String d();\n"
        // Parametrized type, multiple parameters
        + "public abstract Map<String, Number> e();\n"
        // Parametrized type, single parameter
        + "public abstract Set<? extends String> f();\n"
        // Nested parameterized type
        + "public abstract Map<String, Set<? super String>> g();\n"
        // Nullable type
        + "@Nullable abstract String i();\n"
        + "}\n"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Test", ""
        + "package test;\n"
        + "\n"
        + "import com.ryanharter.auto.value.moshi.Nullable;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import com.squareup.moshi.Types;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Integer;\n"
        + "import java.lang.Number;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.util.Map;\n"
        + "import java.util.Set;\n"
        + "\n"
        + "final class AutoValue_Test extends $AutoValue_Test {\n"
        + "  AutoValue_Test(String a, int[] b, int c, String d, Map<String, Number> e, "
        + "     Set<? extends String> f, Map<String, Set<? super String>> g, "
        + "     @Nullable String i) {\n"
        + "    super(a, b, c, d, e, f, g, i);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter extends JsonAdapter<Test> {\n"
        + "  \n"
        + "    private static final String[] NAMES = new String[] {\"a\", \"b\", \"c\", \"d\", "
        + "\"e\", \"f\", \"g\", \"i\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<String> aAdapter;\n"
        + "    private final JsonAdapter<int[]> bAdapter;\n"
        + "    private final JsonAdapter<Integer> cAdapter;\n"
        + "    private final JsonAdapter<String> dAdapter;\n"
        + "    private final JsonAdapter<Map<String, Number>> eAdapter;\n"
        + "    private final JsonAdapter<Set<? extends String>> fAdapter;\n"
        + "    private final JsonAdapter<Map<String, Set<? super String>>> gAdapter;\n"
        + "    private final JsonAdapter<String> iAdapter;\n"
        + "  \n"
        + "    public AutoValue_TestJsonAdapter(Moshi moshi) {\n"
        + "      this.aAdapter = adapter(moshi, String.class);\n"
        + "      this.bAdapter = adapter(moshi, int[].class);\n"
        + "      this.cAdapter = adapter(moshi, int.class);\n"
        + "      this.dAdapter = adapter(moshi, String.class);\n"
        + "      this.eAdapter = adapter(moshi, Types.newParameterizedType(Map.class, "
        + "         String.class, Number.class));\n"
        + "      this.fAdapter = adapter(moshi, Types.newParameterizedType(Set.class, "
        + "         Types.subtypeOf(String.class)));\n"
        + "      this.gAdapter = adapter(moshi, Types.newParameterizedType(Map.class, "
        + "         String.class, Types.newParameterizedType(Set.class, "
        + "             Types.supertypeOf(String.class))));\n"
        + "      this.iAdapter = adapter(moshi, String.class).nullSafe();\n"
        + "    }\n"
        + "  \n"
        + "    @Override public Test fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      String a = null;\n"
        + "      int[] b = null;\n"
        + "      int c = 0;\n"
        + "      String d = null;\n"
        + "      Map<String, Number> e = null;\n"
        + "      Set<? extends String> f = null;\n"
        + "      Map<String, Set<? super String>> g = null;\n"
        + "      String i = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            a = this.aAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            b = this.bAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 2: {\n"
        + "            c = this.cAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 3: {\n"
        + "            d = this.dAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 4: {\n"
        + "            e = this.eAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 5: {\n"
        + "            f = this.fAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 6: {\n"
        + "            g = this.gAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 7: {\n"
        + "            i = this.iAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Test(a, b, c, d, e, f, g, i);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public void toJson(JsonWriter writer, Test value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"a\");\n"
        + "      this.aAdapter.toJson(writer, value.a());\n"
        + "      writer.name(\"b\");\n"
        + "      this.bAdapter.toJson(writer, value.b());\n"
        + "      writer.name(\"c\");\n"
        + "      this.cAdapter.toJson(writer, value.c());\n"
        + "      writer.name(\"d\");\n"
        + "      this.dAdapter.toJson(writer, value.d());\n"
        + "      writer.name(\"e\");\n"
        + "      this.eAdapter.toJson(writer, value.e());\n"
        + "      writer.name(\"f\");\n"
        + "      this.fAdapter.toJson(writer, value.f());\n"
        + "      writer.name(\"g\");\n"
        + "      this.gAdapter.toJson(writer, value.g());\n"
        + "      String i = value.i();"
        + "      if (i != null) {\n"
        + "        writer.name(\"i\");\n"
        + "        this.iAdapter.toJson(writer, i);\n"
        + "      }\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}"
    );

    assertAbout(javaSources())
        .that(Arrays.asList(serializedName, nullable, source))
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void allNullable() {
    JavaFileObject source = JavaFileObjects.forSourceString("test.Test", ""
        + "package test;\n"
        + "import com.squareup.moshi.Json;\n"
        + "import com.ryanharter.auto.value.moshi.SerializedName;\n"
        + "import com.ryanharter.auto.value.moshi.Nullable;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "import java.util.Set;\n"
        + "@AutoValue public abstract class Test {\n"
        + "  public static JsonAdapter<Test> jsonAdapter(Moshi moshi) {\n"
        + "    return new AutoValue_Test.MoshiJsonAdapter(moshi);\n"
        + "  }\n"
        + "@Nullable public abstract String a();\n"
        + "@Nullable public abstract int[] b();\n"
        + "@Nullable public abstract Integer c();\n"
        + "@Nullable public abstract List<String> d();\n"
        + "@Nullable public abstract Map<String, Number> e();\n"
        + "@Nullable public abstract Set<? extends String> f();\n"
        + "@Nullable public abstract Map<String, Set<? super String>> g();\n"
        + "}\n"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Test", ""
        + "package test;\n"
        + "\n"
        + "import com.ryanharter.auto.value.moshi.Nullable;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import com.squareup.moshi.Types;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Integer;\n"
        + "import java.lang.Number;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "import java.util.Set;\n"
        + "\n"
        + "final class AutoValue_Test extends $AutoValue_Test {\n"
        + "  AutoValue_Test(@Nullable String a, @Nullable int[] b, @Nullable Integer c, "
        + "     @Nullable List<String> d, @Nullable Map<String, Number> e, "
        + "     @Nullable Set<? extends String> f, @Nullable Map<String, Set<? super String>> g)"
        + "  {\n"
        + "    super(a, b, c, d, e, f, g);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter extends JsonAdapter<Test> {\n"
        + "  \n"
        + "    private static final String[] NAMES = new String[] {\"a\", \"b\", \"c\", \"d\", "
        + "\"e\", \"f\", \"g\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<String> aAdapter;\n"
        + "    private final JsonAdapter<int[]> bAdapter;\n"
        + "    private final JsonAdapter<Integer> cAdapter;\n"
        + "    private final JsonAdapter<List<String>> dAdapter;\n"
        + "    private final JsonAdapter<Map<String, Number>> eAdapter;\n"
        + "    private final JsonAdapter<Set<? extends String>> fAdapter;\n"
        + "    private final JsonAdapter<Map<String, Set<? super String>>> gAdapter;\n"
        + "  \n"
        + "    public AutoValue_TestJsonAdapter(Moshi moshi) {\n"
        + "      this.aAdapter = adapter(moshi, String.class).nullSafe()\n;"
        + "      this.bAdapter = adapter(moshi, int[].class).nullSafe();\n"
        + "      this.cAdapter = adapter(moshi, Integer.class).nullSafe();\n"
        + "      this.dAdapter = adapter(moshi, Types.newParameterizedType(List.class, "
        + "         String.class)).nullSafe();\n"
        + "      this.eAdapter = adapter(moshi, Types.newParameterizedType(Map.class, "
        + "         String.class, Number.class)).nullSafe();\n"
        + "      this.fAdapter = adapter(moshi, Types.newParameterizedType(Set.class, "
        + "         Types.subtypeOf(String.class))).nullSafe();\n"
        + "      this.gAdapter = adapter(moshi, Types.newParameterizedType(Map.class, "
        + "         String.class, Types.newParameterizedType(Set.class, "
        + "         Types.supertypeOf(String.class)))).nullSafe();\n"
        + "    }\n"
        + "  \n"
        + "    @Override public Test fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      String a = null;\n"
        + "      int[] b = null;\n"
        + "      Integer c = null;\n"
        + "      List<String> d = null;\n"
        + "      Map<String, Number> e = null;\n"
        + "      Set<? extends String> f = null;\n"
        + "      Map<String, Set<? super String>> g = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            a = this.aAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            b = this.bAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 2: {\n"
        + "            c = this.cAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 3: {\n"
        + "            d = this.dAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 4: {\n"
        + "            e = this.eAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 5: {\n"
        + "            f = this.fAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 6: {\n"
        + "            g = this.gAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Test(a, b, c, d, e, f, g);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public void toJson(JsonWriter writer, Test value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      String a = value.a();"
        + "      if (a != null) {\n"
        + "        writer.name(\"a\");\n"
        + "        this.aAdapter.toJson(writer, a);\n"
        + "      }\n"
        + "      int[] b = value.b();"
        + "      if (b != null) {\n"
        + "        writer.name(\"b\");\n"
        + "        this.bAdapter.toJson(writer, b);\n"
        + "      }\n"
        + "      Integer c = value.c();"
        + "      if (c != null) {\n"
        + "        writer.name(\"c\");\n"
        + "        this.cAdapter.toJson(writer, c);\n"
        + "      }\n"
        + "      List<String> d = value.d();"
        + "      if (d != null) {\n"
        + "        writer.name(\"d\");\n"
        + "        this.dAdapter.toJson(writer, d);\n"
        + "      }\n"
        + "      Map<String, Number> e = value.e();"
        + "      if (e != null) {\n"
        + "        writer.name(\"e\");\n"
        + "        this.eAdapter.toJson(writer, e);\n"
        + "      }\n"
        + "      Set<? extends String> f = value.f();"
        + "      if (f != null) {\n"
        + "        writer.name(\"f\");\n"
        + "        this.fAdapter.toJson(writer, f);\n"
        + "      }\n"
        + "      Map<String, Set<? super String>> g = value.g();"
        + "      if (g != null) {\n"
        + "        writer.name(\"g\");\n"
        + "        this.gAdapter.toJson(writer, g);\n"
        + "      }\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}"
    );

    assertAbout(javaSources())
        .that(Arrays.asList(serializedName, nullable, source))
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void nullableWillValueAndWriterAsProperties() {
    JavaFileObject source = JavaFileObjects.forSourceString("test.Test", ""
        + "package test;\n"
        + "import com.squareup.moshi.Json;\n"
        + "import com.ryanharter.auto.value.moshi.Nullable;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "@AutoValue public abstract class Test {\n"
        + "  public static JsonAdapter<Test> jsonAdapter(Moshi moshi) {\n"
        + "    return new AutoValue_Test.MoshiJsonAdapter(moshi);\n"
        + "  }\n"
        + "@Nullable public abstract String value();\n"
        + "@Nullable public abstract String writer();\n"
        + "}\n"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Test", ""
        + "package test;\n"
        + "\n"
        + "import com.ryanharter.auto.value.moshi.Nullable;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "\n"
        + "final class AutoValue_Test extends $AutoValue_Test {\n"
        + "  AutoValue_Test(@Nullable String value, @Nullable String writer) {\n"
        + "    super(value, writer);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter extends JsonAdapter<Test> {\n"
        + "  \n"
        + "    private static final String[] NAMES = new String[] {\"value\", \"writer\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<String> valueAdapter;\n"
        + "    private final JsonAdapter<String> writerAdapter;\n"
        + "  \n"
        + "    public AutoValue_TestJsonAdapter(Moshi moshi) {\n"
        + "      this.valueAdapter = adapter(moshi, String.class).nullSafe();\n"
        + "      this.writerAdapter = adapter(moshi, String.class).nullSafe();\n"
        + "    }\n"
        + "  \n"
        + "    @Override public Test fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      String value = null;\n"
        + "      String writer = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            value = this.valueAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            writer = this.writerAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Test(value, writer);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public void toJson(JsonWriter writer, Test value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      String value_ = value.value();"
        + "      if (value_ != null) {\n"
        + "        writer.name(\"value\");\n"
        + "        this.valueAdapter.toJson(writer, value_);\n"
        + "      }\n"
        + "      String writer_ = value.writer();"
        + "      if (writer_ != null) {\n"
        + "        writer.name(\"writer\");\n"
        + "        this.writerAdapter.toJson(writer, writer_);\n"
        + "      }\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}"
    );

    assertAbout(javaSources())
        .that(Arrays.asList(serializedName, nullable, source))
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void propertyContainsAdapterAsName() {
    JavaFileObject source = JavaFileObjects.forSourceString("test.Test", ""
        + "package test;\n"
        + "import com.squareup.moshi.Json;\n"
        + "import com.ryanharter.auto.value.moshi.Nullable;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "@AutoValue public abstract class Test {\n"
        + "  public static JsonAdapter<Test> jsonAdapter(Moshi moshi) {\n"
        + "    return new AutoValue_Test.MoshiJsonAdapter(moshi);\n"
        + "  }\n"
        + "@Nullable public abstract String a();\n"
        + "@Nullable public abstract String aAdapter();\n"
        + "}\n"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Test", ""
        + "package test;\n"
        + "\n"
        + "import com.ryanharter.auto.value.moshi.Nullable;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "\n"
        + "final class AutoValue_Test extends $AutoValue_Test {\n"
        + "  AutoValue_Test(@Nullable String a, @Nullable String aAdapter) {\n"
        + "    super(a, aAdapter);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter extends JsonAdapter<Test> {\n"
        + "  \n"
        + "    private static final String[] NAMES = new String[] {\"a\", \"aAdapter\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<String> aAdapter;\n"
        + "    private final JsonAdapter<String> aAdapterAdapter;\n"
        + "  \n"
        + "    public AutoValue_TestJsonAdapter(Moshi moshi) {\n"
        + "      this.aAdapter = adapter(moshi, String.class).nullSafe();\n"
        + "      this.aAdapterAdapter = adapter(moshi, String.class).nullSafe();"
        + "    }\n"
        + "  \n"
        + "    @Override public Test fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      String a = null;\n"
        + "      String aAdapter = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            a = this.aAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            aAdapter = this.aAdapterAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Test(a, aAdapter);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public void toJson(JsonWriter writer, Test value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      String a = value.a();"
        + "      if (a != null) {\n"
        + "        writer.name(\"a\");\n"
        + "        this.aAdapter.toJson(writer, a);\n"
        + "      }\n"
        + "      String aAdapter = value.aAdapter();"
        + "      if (aAdapter != null) {\n"
        + "        writer.name(\"aAdapter\");\n"
        + "        this.aAdapterAdapter.toJson(writer, aAdapter);\n"
        + "      }\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}"
    );

    assertAbout(javaSources())
        .that(Arrays.asList(serializedName, nullable, source))
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void propertyMethodReferencedWithPrefix() {
    JavaFileObject source = JavaFileObjects.forSourceString("test.Test", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "@AutoValue public abstract class Test {\n"
        + "  public static JsonAdapter<Test> jsonAdapter(Moshi moshi) {\n"
        + "    return new AutoValue_Test.MoshiJsonAdapter(moshi);\n"
        + "  }\n"
        + "  public abstract String getName();\n"
        + "  public abstract boolean isAwesome();\n"
        + "}"
    );
    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Test", ""
        + "package test;\n"
        + "\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Boolean;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "\n"
        + "final class AutoValue_Test extends $AutoValue_Test {\n"
        + "  AutoValue_Test(String name, boolean awesome) {\n"
        + "    super(name, awesome);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter extends JsonAdapter<Test> {\n"
        + "    private static final String[] NAMES = new String[] {\"name\", \"awesome\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<String> nameAdapter;\n"
        + "    private final JsonAdapter<Boolean> awesomeAdapter;\n"
        + "    public AutoValue_TestJsonAdapter(Moshi moshi) {\n"
        + "      this.nameAdapter = adapter(moshi, String.class);\n"
        + "      this.awesomeAdapter = adapter(moshi, boolean.class);\n"
        + "    }\n"
        + "    @Override\n"
        + "    public Test fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      String name = null;\n"
        + "      boolean awesome = false;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            name = this.nameAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            awesome = this.awesomeAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Test(name, awesome);\n"
        + "    }\n"
        + "    @Override\n"
        + "    public void toJson(JsonWriter writer, Test value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"name\");\n"
        + "      this.nameAdapter.toJson(writer, value.getName());\n"
        + "      writer.name(\"awesome\");\n"
        + "      this.awesomeAdapter.toJson(writer, value.isAwesome());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}");

    assertAbout(javaSources())
        .that(Arrays.asList(source, nullable))
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void usesJsonQualifierAnnotations() {
    JavaFileObject annotation = JavaFileObjects.forSourceString("test.FooPrefix", ""
        + "package test;\n"
        + "import com.squareup.moshi.JsonQualifier;\n"
        + "import java.lang.annotation.Retention;\n"
        + "import static java.lang.annotation.RetentionPolicy.RUNTIME;\n"
        + "@Retention(RUNTIME)\n"
        + "@JsonQualifier\n"
        + "public @interface FooPrefix {\n"
        + "}\n"
    );
    JavaFileObject adapter = JavaFileObjects.forSourceString("test.FooPrefixAdapter", ""
        + "package test;\n"
        + "import com.squareup.moshi.ToJson;\n"
        + "import com.squareup.moshi.FromJson;\n"
        + "import com.squareup.moshi.JsonDataException;\n"
        + "class FooPrefixAdapter {\n"
        + "  @ToJson String fooPrefixStringToString(@FooPrefix String s) {\n"
        + "    return \"foo\" + s;\n"
        + "  }\n"
        + "  @FromJson @FooPrefix String fooPrefixStringFromString(String s) {\n"
        + "    if (!s.startsWith(\"foo\")) throw new JsonDataException();\n"
        + "    return s.substring(3);\n"
        + "  }\n"
        + "}"
    );
    JavaFileObject source = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "@AutoValue public abstract class Foo {\n"
        + "  public static JsonAdapter<Foo> jsonAdapter(Moshi moshi) {\n"
        + "    return new AutoValue_Foo.MoshiJsonAdapter(moshi);\n"
        + "  }\n"
        + "  public abstract String a();\n"
        + "  public abstract @FooPrefix String b();\n"
        + "}\n"
    );
    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Foo", ""
        + "package test;\n"
        + "\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonQualifier;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import com.squareup.moshi.Types;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.NoSuchMethodException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.annotation.Annotation;\n"
        + "import java.lang.reflect.Method;\n"
        + "import java.lang.reflect.ParameterizedType;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.lang.reflect.TypeVariable;\n"
        + "import java.util.LinkedHashSet;\n"
        + "import java.util.Set;\n"
        + "\n"
        + "final class AutoValue_Foo extends $AutoValue_Foo {\n"
        + "  AutoValue_Foo(String a, String b) {\n"
        + "    super(a, b);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter extends JsonAdapter<Foo> {\n"
        + "    private static final String[] NAMES = new String[] {\"a\",\"b\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<String> aAdapter;\n"
        + "    private final JsonAdapter<String> bAdapter;\n"
        + "    public AutoValue_FooJsonAdapter(Moshi moshi) {\n"
        + "      this.aAdapter = adapter(moshi, String.class);\n"
        + "      this.bAdapter = adapterWithQualifier(moshi, \"b\", null);\n"
        + "    }\n"
        + "    @Override\n"
        + "    public Foo fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      String a = null;\n"
        + "      String b = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            a = this.aAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            b = this.bAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Foo(a, b);\n"
        + "    }\n"
        + "    @Override\n"
        + "    public void toJson(JsonWriter writer, Foo value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"a\");\n"
        + "      this.aAdapter.toJson(writer, value.a());\n"
        + "      writer.name(\"b\");\n"
        + "      this.bAdapter.toJson(writer, value.b());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "    private JsonAdapter adapterWithQualifier(Moshi moshi, String methodName,\n"
        + "                                             Type declaredGenericType) {\n"
        + "      try {\n"
        + "        Method method = Foo.class.getMethod(methodName);\n"
        + "        Set<Annotation> annotations = new LinkedHashSet<>();\n"
        + "        for (Annotation annotation : method.getAnnotations()) {\n"
        + "          if (annotation.annotationType().isAnnotationPresent(JsonQualifier.class)) {\n"
        + "            annotations.add(annotation);\n"
        + "          }\n"
        + "        }\n"
        + "        Type adapterType = method.getGenericReturnType();\n"
        + "        if (declaredGenericType != null) {\n"
        + "          if (adapterType instanceof ParameterizedType) {\n"
        + "            adapterType = Types.newParameterizedType(\n"
        + "               ((ParameterizedType) adapterType).getRawType(), declaredGenericType);\n"
        + "          }\n"
        + "          else if (adapterType instanceof TypeVariable) {\n"
        + "            adapterType = declaredGenericType;\n"
        + "          }\n"
        + "        }\n"
        + "        return moshi.adapter(adapterType, annotations);\n"
        + "      } catch (NoSuchMethodException e) {\n"
        + "        throw new RuntimeException(\"No method named \" + methodName, e);\n"
        + "      }\n"
        + "    }\n"
        + "  }\n"
        + "}");

    assertAbout(javaSources())
        .that(Arrays.asList(annotation, adapter, source))
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void usesJsonQualifierAnnotationsWithBaseInterface() {
    JavaFileObject annotation = JavaFileObjects.forSourceString("test.FooPrefix", ""
        + "package test;\n"
        + "import com.squareup.moshi.JsonQualifier;\n"
        + "import java.lang.annotation.Retention;\n"
        + "import static java.lang.annotation.RetentionPolicy.RUNTIME;\n"
        + "@Retention(RUNTIME)\n"
        + "@JsonQualifier\n"
        + "public @interface FooPrefix {\n"
        + "}\n"
    );
    JavaFileObject adapter = JavaFileObjects.forSourceString("test.FooPrefixAdapter", ""
        + "package test;\n"
        + "import com.squareup.moshi.ToJson;\n"
        + "import com.squareup.moshi.FromJson;\n"
        + "import com.squareup.moshi.JsonDataException;\n"
        + "class FooPrefixAdapter {\n"
        + "  @ToJson String fooPrefixStringToString(@FooPrefix String s) {\n"
        + "    return \"foo\" + s;\n"
        + "  }\n"
        + "  @FromJson @FooPrefix String fooPrefixStringFromString(String s) {\n"
        + "    if (!s.startsWith(\"foo\")) throw new JsonDataException();\n"
        + "    return s.substring(3);\n"
        + "  }\n"
        + "}"
    );

    JavaFileObject sourceInterface = JavaFileObjects.forSourceString("test.BaseFoo", ""
        + "package test;\n"
        + "public interface BaseFoo {\n"
        + "  @FooPrefix String a();\n"
        + "}\n"
    );

    JavaFileObject source = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "@AutoValue public abstract class Foo implements BaseFoo {\n"
        + "  public static JsonAdapter<Foo> jsonAdapter(Moshi moshi) {\n"
        + "    return new AutoValue_Foo.MoshiJsonAdapter(moshi);\n"
        + "  }\n"
        + "  public abstract String b();\n"
        + "}\n"
    );
    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Foo", ""
        + "package test;\n"
        + "\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonQualifier;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import com.squareup.moshi.Types;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.NoSuchMethodException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.annotation.Annotation;\n"
        + "import java.lang.reflect.Method;\n"
        + "import java.lang.reflect.ParameterizedType;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.lang.reflect.TypeVariable;\n"
        + "import java.util.LinkedHashSet;\n"
        + "import java.util.Set;\n"
        + "\n"
        + "final class AutoValue_Foo extends $AutoValue_Foo {\n"
        + "  AutoValue_Foo(String a, String b) {\n"
        + "    super(a, b);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter extends JsonAdapter<Foo> {\n"
        + "    private static final String[] NAMES = new String[] {\"a\",\"b\"};\n"
        + "    private static final JsonReader.Options OPTIONS ="
        + " JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<String> aAdapter;\n"
        + "    private final JsonAdapter<String> bAdapter;\n"
        + "    public AutoValue_FooJsonAdapter(Moshi moshi) {\n"
        + "      this.aAdapter = adapterWithQualifier(moshi, \"a\", null);\n"
        + "      this.bAdapter = adapter(moshi, String.class);\n"
        + "    }\n"
        + "    @Override\n"
        + "    public Foo fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      String a = null;\n"
        + "      String b = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            a = this.aAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            b = this.bAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Foo(a, b);\n"
        + "    }\n"
        + "    @Override\n"
        + "    public void toJson(JsonWriter writer, Foo value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"a\");\n"
        + "      this.aAdapter.toJson(writer, value.a());\n"
        + "      writer.name(\"b\");\n"
        + "      this.bAdapter.toJson(writer, value.b());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "    private JsonAdapter adapterWithQualifier(Moshi moshi, String methodName,\n"
        + "                                             Type declaredGenericType) {\n"
        + "      try {\n"
        + "        Method method = Foo.class.getMethod(methodName);\n"
        + "        Set<Annotation> annotations = new LinkedHashSet<>();\n"
        + "        for (Annotation annotation : method.getAnnotations()) {\n"
        + "          if (annotation.annotationType().isAnnotationPresent(JsonQualifier.class)) {\n"
        + "            annotations.add(annotation);\n"
        + "          }\n"
        + "        }\n"
        + "        Type adapterType = method.getGenericReturnType();\n"
        + "        if (declaredGenericType != null) {\n"
        + "          if (adapterType instanceof ParameterizedType) {\n"
        + "            adapterType = Types.newParameterizedType(\n"
        + "               ((ParameterizedType) adapterType).getRawType(), declaredGenericType);\n"
        + "          }\n"
        + "          else if (adapterType instanceof TypeVariable) {\n"
        + "            adapterType = declaredGenericType;\n"
        + "          }\n"
        + "        }\n"
        + "        return moshi.adapter(adapterType, annotations);\n"
        + "      } catch (NoSuchMethodException e) {\n"
        + "        throw new RuntimeException(\"No method named \" + methodName, e);\n"
        + "      }\n"
        + "    }\n"
        + "  }\n"
        + "}");

    assertAbout(javaSources())
            .that(Arrays.asList(annotation, adapter, source, sourceInterface))
            .processedWith(new AutoValueProcessor())
            .compilesWithoutError()
            .and()
            .generatesSources(expected);
  }

  @Test public void usesJsonQualifierAnnotationsWithBaseAbstractClass() {
    JavaFileObject annotation = JavaFileObjects.forSourceString("test.FooPrefix", ""
        + "package test;\n"
        + "import com.squareup.moshi.JsonQualifier;\n"
        + "import java.lang.annotation.Retention;\n"
        + "import static java.lang.annotation.RetentionPolicy.RUNTIME;\n"
        + "@Retention(RUNTIME)\n"
        + "@JsonQualifier\n"
        + "public @interface FooPrefix {\n"
        + "}\n"
    );
    JavaFileObject adapter = JavaFileObjects.forSourceString("test.FooPrefixAdapter", ""
        + "package test;\n"
        + "import com.squareup.moshi.ToJson;\n"
        + "import com.squareup.moshi.FromJson;\n"
        + "import com.squareup.moshi.JsonDataException;\n"
        + "class FooPrefixAdapter {\n"
        + "  @ToJson String fooPrefixStringToString(@FooPrefix String s) {\n"
        + "    return \"foo\" + s;\n"
        + "  }\n"
        + "  @FromJson @FooPrefix String fooPrefixStringFromString(String s) {\n"
        + "    if (!s.startsWith(\"foo\")) throw new JsonDataException();\n"
        + "    return s.substring(3);\n"
        + "  }\n"
        + "}"
    );

    JavaFileObject sourceInterface = JavaFileObjects.forSourceString("test.BaseFoo", ""
        + "package test;\n"
        + "public abstract class BaseFoo {\n"
        + "  public abstract @FooPrefix String a();\n"
        + "}\n"
    );

    JavaFileObject source = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "@AutoValue public abstract class Foo extends BaseFoo {\n"
        + "  public static JsonAdapter<Foo> jsonAdapter(Moshi moshi) {\n"
        + "    return new AutoValue_Foo.MoshiJsonAdapter(moshi);\n"
        + "  }\n"
        + "  public abstract String b();\n"
        + "}\n"
    );
    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Foo", ""
        + "package test;\n"
        + "\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonQualifier;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import com.squareup.moshi.Types;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.NoSuchMethodException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.annotation.Annotation;\n"
        + "import java.lang.reflect.Method;\n"
        + "import java.lang.reflect.ParameterizedType;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.lang.reflect.TypeVariable;\n"
        + "import java.util.LinkedHashSet;\n"
        + "import java.util.Set;\n"
        + "\n"
        + "final class AutoValue_Foo extends $AutoValue_Foo {\n"
        + "  AutoValue_Foo(String a, String b) {\n"
        + "    super(a, b);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter extends JsonAdapter<Foo> {\n"
        + "    private static final String[] NAMES = new String[] {\"a\",\"b\"};\n"
        + "    private static final JsonReader.Options OPTIONS ="
        + " JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<String> aAdapter;\n"
        + "    private final JsonAdapter<String> bAdapter;\n"
        + "    public AutoValue_FooJsonAdapter(Moshi moshi) {\n"
        + "      this.aAdapter = adapterWithQualifier(moshi, \"a\", null);\n"
        + "      this.bAdapter = adapter(moshi, String.class);\n"
        + "    }\n"
        + "    @Override\n"
        + "    public Foo fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      String a = null;\n"
        + "      String b = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            a = this.aAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            b = this.bAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Foo(a, b);\n"
        + "    }\n"
        + "    @Override\n"
        + "    public void toJson(JsonWriter writer, Foo value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"a\");\n"
        + "      this.aAdapter.toJson(writer, value.a());\n"
        + "      writer.name(\"b\");\n"
        + "      this.bAdapter.toJson(writer, value.b());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "    private JsonAdapter adapterWithQualifier(Moshi moshi, String methodName,\n"
        + "                                             Type declaredGenericType) {\n"
        + "      try {\n"
        + "        Method method = Foo.class.getMethod(methodName);\n"
        + "        Set<Annotation> annotations = new LinkedHashSet<>();\n"
        + "        for (Annotation annotation : method.getAnnotations()) {\n"
        + "          if (annotation.annotationType().isAnnotationPresent(JsonQualifier.class)) {\n"
        + "            annotations.add(annotation);\n"
        + "          }\n"
        + "        }\n"
        + "        Type adapterType = method.getGenericReturnType();\n"
        + "        if (declaredGenericType != null) {\n"
        + "          if (adapterType instanceof ParameterizedType) {\n"
        + "            adapterType = Types.newParameterizedType(\n"
        + "               ((ParameterizedType) adapterType).getRawType(), declaredGenericType);\n"
        + "          }\n"
        + "          else if (adapterType instanceof TypeVariable) {\n"
        + "            adapterType = declaredGenericType;\n"
        + "          }\n"
        + "        }\n"
        + "        return moshi.adapter(adapterType, annotations);\n"
        + "      } catch (NoSuchMethodException e) {\n"
        + "        throw new RuntimeException(\"No method named \" + methodName, e);\n"
        + "      }\n"
        + "    }\n"
        + "  }\n"
        + "}");

    assertAbout(javaSources())
            .that(Arrays.asList(annotation, adapter, source, sourceInterface))
            .processedWith(new AutoValueProcessor())
            .compilesWithoutError()
            .and()
            .generatesSources(expected);
  }

  @Test public void usesDefaults() {
    JavaFileObject source = JavaFileObjects.forSourceString("test.Test", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "@AutoValue public abstract class Test {\n"
        + "  public static JsonAdapter<Test> jsonAdapter(Moshi moshi) {\n"
        + "    return AutoValue_Test.jsonAdapter(moshi);\n"
        + "  }\n"
        + "  public abstract boolean a();\n"
        + "  public abstract byte b();\n"
        + "  public abstract short c();\n"
        + "  public abstract int d();\n"
        + "  public abstract long e();\n"
        + "  public abstract char f();\n"
        + "  public abstract float g();\n"
        + "  public abstract double h();\n"
        + "  public abstract Object i();\n"
        + "}\n"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Test", ""
        + "package test;\n"
        + "\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Boolean;\n"
        + "import java.lang.Byte;\n"
        + "import java.lang.Character;\n"
        + "import java.lang.Double;\n"
        + "import java.lang.Float;\n"
        + "import java.lang.Integer;\n"
        + "import java.lang.Long;\n"
        + "import java.lang.Object;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.Short;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "\n"
        + "final class AutoValue_Test extends $AutoValue_Test {\n"
        + "  AutoValue_Test(boolean a, byte b, short c, int d, long e, char f, float g, double h,"
        + "      Object i) {\n"
        + "    super(a, b, c, d, e, f, g, h, i);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter extends JsonAdapter<Test> {\n"
        + "    private static final String[] NAMES = new String[] {\"a\", \"b\", \"c\", \"d\", "
        + "\"e\", \"f\", \"g\", \"h\", \"i\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<Boolean> aAdapter;\n"
        + "    private final JsonAdapter<Byte> bAdapter;\n"
        + "    private final JsonAdapter<Short> cAdapter;\n"
        + "    private final JsonAdapter<Integer> dAdapter;\n"
        + "    private final JsonAdapter<Long> eAdapter;\n"
        + "    private final JsonAdapter<Character> fAdapter;\n"
        + "    private final JsonAdapter<Float> gAdapter;\n"
        + "    private final JsonAdapter<Double> hAdapter;\n"
        + "    private final JsonAdapter<Object> iAdapter;\n"
        + "    public MoshiJsonAdapter(Moshi moshi) {\n"
        + "      this.aAdapter = adapter(moshi, boolean.class);\n"
        + "      this.bAdapter = adapter(moshi, byte.class);\n"
        + "      this.cAdapter = adapter(moshi, short.class);\n"
        + "      this.dAdapter = adapter(moshi, int.class);\n"
        + "      this.eAdapter = adapter(moshi, long.class);\n"
        + "      this.fAdapter = adapter(moshi, char.class);\n"
        + "      this.gAdapter = adapter(moshi, float.class);\n"
        + "      this.hAdapter = adapter(moshi, double.class);\n"
        + "      this.iAdapter = adapter(moshi, Object.class);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public Test fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      boolean a = false;\n"
        + "      byte b = (byte) 0;\n"
        + "      short c = 0;\n"
        + "      int d = 0;\n"
        + "      long e = 0L;\n"
        + "      char f = '\0';\n"
        + "      float g = 0.0f;\n"
        + "      double h = 0.0d;\n"
        + "      Object i = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            a = this.aAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            b = this.bAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 2: {\n"
        + "            c = this.cAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 3: {\n"
        + "            d = this.dAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 4: {\n"
        + "            e = this.eAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 5: {\n"
        + "            f = this.fAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 6: {\n"
        + "            g = this.gAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 7: {\n"
        + "            h = this.hAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 8: {\n"
        + "            i = this.iAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Test(a, b, c, d, e, f, g, h, i);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public void toJson(JsonWriter writer, Test value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"a\");\n"
        + "      this.aAdapter.toJson(writer, value.a());\n"
        + "      writer.name(\"b\");\n"
        + "      this.bAdapter.toJson(writer, value.b());\n"
        + "      writer.name(\"c\");\n"
        + "      this.cAdapter.toJson(writer, value.c());\n"
        + "      writer.name(\"d\");\n"
        + "      this.dAdapter.toJson(writer, value.d());\n"
        + "      writer.name(\"e\");\n"
        + "      this.eAdapter.toJson(writer, value.e());\n"
        + "      writer.name(\"f\");\n"
        + "      this.fAdapter.toJson(writer, value.f());\n"
        + "      writer.name(\"g\");\n"
        + "      this.gAdapter.toJson(writer, value.g());\n"
        + "      writer.name(\"h\");\n"
        + "      this.hAdapter.toJson(writer, value.h());\n"
        + "      writer.name(\"i\");\n"
        + "      this.iAdapter.toJson(writer, value.i());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}"
    );

    assertAbout(javaSource())
        .that(source)
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void generatesNothingWithoutJsonAdapterMethod() {
    JavaFileObject source = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "@AutoValue public abstract class Foo {\n"
        + "  public abstract String a();\n"
        + "  public abstract String b();\n"
        + "}\n"
    );
    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Foo",
            "package test;\n"
        + "\n"
        + "import javax.annotation.Generated;\n"
        + "\n"
        + "@Generated(\"com.google.auto.value.processor.AutoValueProcessor\")\n"
        + "final class AutoValue_Foo extends Foo {\n"
        + "\n"
        + "    private final String a;\n"
        + "\n"
        + "    private final String b;\n"
        + "\n"
        + "    AutoValue_Foo(\n"
        + "            String a,\n"
        + "            String b) {\n"
        + "        if (a == null) {\n"
        + "            throw new NullPointerException(\"Null a\");\n"
        + "        }\n"
        + "        this.a = a;\n"
        + "        if (b == null) {\n"
        + "            throw new NullPointerException(\"Null b\");\n"
        + "        }\n"
        + "        this.b = b;\n"
        + "    }\n"
        + "\n"
        + "    @Override\n"
        + "    public String a() {\n"
        + "        return a;\n"
        + "    }\n"
        + "\n"
        + "    @Override\n"
        + "    public String b() {\n"
        + "        return b;\n"
        + "    }\n"
        + "\n"
        + "    @Override\n"
        + "    public String toString() {\n"
        + "        return \"Foo{\"\n"
        + "                + \"a=\" + a + \", \"\n"
        + "                + \"b=\" + b\n"
        + "                + \"}\";\n"
        + "    }\n"
        + "\n"
        + "    @Override\n"
        + "    public boolean equals(Object o) {\n"
        + "        if (o == this) {\n"
        + "            return true;\n"
        + "        }\n"
        + "        if (o instanceof Foo) {\n"
        + "            Foo that = (Foo) o;\n"
        + "            return (this.a.equals(that.a()))\n"
        + "                    && (this.b.equals(that.b()));\n"
        + "        }\n"
        + "        return false;\n"
        + "    }\n"
        + "\n"
        + "    @Override\n"
        + "    public int hashCode() {\n"
        + "        int h$ = 1;\n"
        + "        h$ *= 1000003;\n"
        + "        h$ ^= a.hashCode();\n"
        + "        h$ *= 1000003;\n"
        + "        h$ ^= b.hashCode();\n"
        + "        return h$;\n"
        + "    }\n"
        + "\n"
        + "}");

    assertAbout(javaSource())
        .that(source)
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .withWarningCount(2)
        .and()
        .generatesSources(expected);
  }

  @Test public void emitsWarningForWrongTypeAdapterTypeArgument() {
    JavaFileObject source1 = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "@AutoValue public abstract class Foo {\n"
        + "  public static JsonAdapter<Bar> jsonAdapter(Moshi moshi) {\n"
        + "    return null;"
        + "  }\n"
        + "  public abstract String a();\n"
        + "  public abstract boolean b();\n"
        + "}"
    );

    JavaFileObject source2 = JavaFileObjects.forSourceString("test.Bar", ""
        + "package test;\n"
        + "public class Bar {\n"
        + "}");

    assertAbout(javaSources())
        .that(ImmutableSet.of(source1, source2))
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .withWarningContaining("Found static method returning JsonAdapter<test.Bar> on "
            + "test.Foo class. Skipping MoshiJsonAdapter generation.");
  }

  @Test public void emitsWarningForNoTypeAdapterTypeArgument() {
    JavaFileObject source1 = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "@AutoValue public abstract class Foo {\n"
        + "  public static JsonAdapter jsonAdapter(Moshi moshi) {\n"
        + "    return null;"
        + "  }\n"
        + "  public abstract String a();\n"
        + "  public abstract boolean b();\n"
        + "}"
    );

    assertAbout(javaSource())
        .that(source1)
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .withWarningContaining("Found static method returning JsonAdapter with no type "
            + "arguments, skipping MoshiJsonAdapter generation.");
  }

  @Test public void handlesConflictingVariableNames() {
    JavaFileObject source1 = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "@AutoValue public abstract class Foo {\n"
        + "  public static JsonAdapter<Foo> jsonAdapter(Moshi moshi) {\n"
        + "    return null;"
        + "  }\n"
        + "  public abstract String reader();\n"
        + "  public abstract String name();\n"
        + "}"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Foo", ""
        + "package test;\n"
        + "\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "\n"
        + "final class AutoValue_Foo extends $AutoValue_Foo {\n"
        + "  AutoValue_Foo(String reader, String name) {\n"
        + "    super(reader, name);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter extends JsonAdapter<Foo> {\n"
        + "    private static final String[] NAMES = new String[] {\"reader\", \"name\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<String> readerAdapter;\n"
        + "    private final JsonAdapter<String> nameAdapter;\n"
        + "    public MoshiJsonAdapter(Moshi moshi) {\n"
        + "      this.readerAdapter = adapter(moshi, String.class);\n"
        + "      this.nameAdapter = adapter(moshi, String.class);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public Foo fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      String reader_ = null;\n"
        + "      String name = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            reader_ = this.readerAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            name = this.nameAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Foo(reader_, name);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public void toJson(JsonWriter writer, Foo value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"reader\");\n"
        + "      this.readerAdapter.toJson(writer, value.reader());\n"
        + "      writer.name(\"name\");\n"
        + "      this.nameAdapter.toJson(writer, value.name());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}"
    );

    assertAbout(javaSource())
        .that(source1)
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void singleGenericAsParameter() {
    JavaFileObject source1 = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.util.List;\n"
        + "@AutoValue public abstract class Foo<V> {\n"
        + "  public static <T>JsonAdapter<Foo<T>> jsonAdapter(Moshi moshi, Type[] types) {\n"
        + "    return null;"
        + "  }\n"
        + "  public abstract List<V> items();\n"
        + "  public abstract String name();\n"
        + "}"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Foo", ""
        + "package test;\n"
        + "\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import com.squareup.moshi.Types;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.util.List;\n"
        + "\n"
        + "final class AutoValue_Foo<V> extends $AutoValue_Foo<V> {\n"
        + "  AutoValue_Foo(List<V> items, String name) {\n"
        + "    super(items, name);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter<V> extends JsonAdapter<Foo<V>> {\n"
        + "    private static final String[] NAMES = new String[] {\"items\", \"name\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<List<V>> itemsAdapter;\n"
        + "    private final JsonAdapter<String> nameAdapter;\n"

        + "    public MoshiJsonAdapter(Moshi moshi, Type[] types) {\n"
        + "      this.itemsAdapter = adapter(moshi, Types.newParameterizedType(List.class, "
        + "        types[0]));\n"
        + "      this.nameAdapter = adapter(moshi, String.class);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public Foo<V> fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      List<V> items = null;\n"
        + "      String name = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            items = this.itemsAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            name = this.nameAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Foo(items, name);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public void toJson(JsonWriter writer, Foo<V> value) "
        + "        throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"items\");\n"
        + "      this.itemsAdapter.toJson(writer, value.items());\n"
        + "      writer.name(\"name\");\n"
        + "      this.nameAdapter.toJson(writer, value.name());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}"
    );

    assertAbout(javaSource())
        .that(source1)
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void singleGeneric() {
    JavaFileObject source1 = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.lang.reflect.Type;\n"
        + "@AutoValue public abstract class Foo<V> {\n"
        + "  public static <T>JsonAdapter<Foo<T>> jsonAdapter(Moshi moshi, Type[] types) {\n"
        + "    return null;"
        + "  }\n"
        + "  public abstract V item();\n"
        + "  public abstract String name();\n"
        + "}"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Foo", ""
        + "package test;\n"
        + "\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "\n"
        + "final class AutoValue_Foo<V> extends $AutoValue_Foo<V> {\n"
        + "  AutoValue_Foo(V item, String name) {\n"
        + "    super(item, name);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter<V> extends JsonAdapter<Foo<V>> {\n"
        + "    private static final String[] NAMES = new String[] {\"item\",\"name\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<V> itemAdapter;\n"
        + "    private final JsonAdapter<String> nameAdapter;\n"

        + "    public MoshiJsonAdapter(Moshi moshi, Type[] types) {\n"
        + "      this.itemAdapter = adapter(moshi, types[0]);\n"
        + "      this.nameAdapter = adapter(moshi, String.class);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public Foo<V> fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      V item = null;\n"
        + "      String name = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            item = this.itemAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            name = this.nameAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Foo(item, name);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public void toJson(JsonWriter writer, Foo<V> value) "
        + "        throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"item\");\n"
        + "      this.itemAdapter.toJson(writer, value.item());\n"
        + "      writer.name(\"name\");\n"
        + "      this.nameAdapter.toJson(writer, value.name());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}"
    );

    assertAbout(javaSource())
        .that(source1)
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void multipleGenerics() {
    JavaFileObject source1 = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.util.List;\n"
        + "@AutoValue public abstract class Foo<V, T> {\n"
        + "  public static <V, T>JsonAdapter<Foo<V, T>> jsonAdapter(Moshi moshi, "
        + "      Type[] types) {\n"
        + "    return null;"
        + "  }\n"
        + "  public abstract List<V> items();\n"
        + "  public abstract List<T> headers();\n"
        + "}"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Foo", ""
        + "package test;\n"
        + "\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import com.squareup.moshi.Types;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.util.List;\n"
        + "\n"
        + "final class AutoValue_Foo<V, T> extends $AutoValue_Foo<V, T> {\n"
        + "  AutoValue_Foo(List<V> items, List<T> headers) {\n"
        + "    super(items, headers);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter<V, T> "
        + "      extends JsonAdapter<Foo<V, T>> {\n"
        + "    private static final String[] NAMES = new String[] {\"items\", \"headers\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<List<V>> itemsAdapter;\n"
        + "    private final JsonAdapter<List<T>> headersAdapter;\n"
        + "\n"
        + "    public MoshiJsonAdapter(Moshi moshi, Type[] types) {\n"
        + "      this.itemsAdapter = adapter(moshi, Types.newParameterizedType(List.class, "
        + "        types[0]));\n"
        + "      this.headersAdapter = adapter(moshi, Types.newParameterizedType(List.class, "
        + "        types[1]));\n"
        + "    }\n"
        + "  \n"
        + "    @Override public Foo<V, T> fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      List<V> items = null;\n"
        + "      List<T> headers = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            items = this.itemsAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            headers = this.headersAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Foo(items, headers);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public void toJson(JsonWriter writer, Foo<V, T> value) "
        + "        throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"items\");\n"
        + "      this.itemsAdapter.toJson(writer, value.items());\n"
        + "      writer.name(\"headers\");\n"
        + "      this.headersAdapter.toJson(writer, value.headers());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}"
    );

    assertAbout(javaSource())
        .that(source1)
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and()
        .generatesSources(expected);
  }

  @Test public void multipleGenericsNotInOrder() {
    JavaFileObject source1 = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.util.List;\n"
        + "@AutoValue public abstract class Foo<V, T> {\n"
        + "  public static <V, T>JsonAdapter<Foo<V, T>> jsonAdapter(Moshi moshi, "
        + "      Type[] types) {\n"
        + "    return null;"
        + "  }\n"
        + "  public abstract List<T> items();\n"
        + "  public abstract List<V> headers();\n"
        + "}"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Foo", ""
        + "package test;\n"
        + "\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import com.squareup.moshi.Types;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.util.List;\n"
        + "\n"
        + "final class AutoValue_Foo<V, T> extends $AutoValue_Foo<V, T> {\n"
        + "  AutoValue_Foo(List<T> items, List<V> headers) {\n"
        + "    super(items, headers);\n"
        + "  }\n"
        + "\n"
        + "  public static final class MoshiJsonAdapter<V, T> "
        + "      extends JsonAdapter<Foo<V, T>> {\n"
        + "    private static final String[] NAMES = new String[] {\"items\", \"headers\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<List<T>> itemsAdapter;\n"
        + "    private final JsonAdapter<List<V>> headersAdapter;\n"
        + "\n"
        + "    public MoshiJsonAdapter(Moshi moshi, Type[] types) {\n"
        + "      this.itemsAdapter = adapter(moshi, Types.newParameterizedType(List.class, "
        + "        types[1]));\n"
        + "      this.headersAdapter = adapter(moshi, Types.newParameterizedType(List.class, "
        + "        types[0]));\n"
        + "    }\n"
        + "  \n"
        + "    @Override public Foo<V, T> fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      List<T> items = null;\n"
        + "      List<V> headers = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            items = this.itemsAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            headers = this.headersAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unrecognized name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Foo(items, headers);\n"
        + "    }\n"
        + "  \n"
        + "    @Override public void toJson(JsonWriter writer, Foo<V, T> value) "
        + "        throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"items\");\n"
        + "      this.itemsAdapter.toJson(writer, value.items());\n"
        + "      writer.name(\"headers\");\n"
        + "      this.headersAdapter.toJson(writer, value.headers());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "  }\n"
        + "}"
    );

    assertAbout(javaSource())
        .that(source1)
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and().generatesSources(expected);
  }

  @Test public void genericsAndQualifiers() {
    JavaFileObject annotation = JavaFileObjects.forSourceString("test.FooPrefix", ""
        + "package test;\n"
        + "import com.squareup.moshi.JsonQualifier;\n"
        + "import java.lang.annotation.Retention;\n"
        + "import static java.lang.annotation.RetentionPolicy.RUNTIME;\n"
        + "@Retention(RUNTIME)\n"
        + "@JsonQualifier\n"
        + "public @interface FooPrefix {\n"
        + "}\n"
    );
    JavaFileObject adapter = JavaFileObjects.forSourceString("test.FooPrefixAdapter", ""
        + "package test;\n"
        + "import com.squareup.moshi.ToJson;\n"
        + "import com.squareup.moshi.FromJson;\n"
        + "import com.squareup.moshi.JsonDataException;\n"
        + "class FooPrefixAdapter {\n"
        + "  @ToJson String fooPrefixStringToString(@FooPrefix String s) {\n"
        + "    return \"foo\" + s;\n"
        + "  }\n"
        + "  @FromJson @FooPrefix String fooPrefixStringFromString(String s) {\n"
        + "    if (!s.startsWith(\"foo\")) throw new JsonDataException();\n"
        + "    return s.substring(3);\n"
        + "  }\n"
        + "}"
    );
    JavaFileObject source = JavaFileObjects.forSourceString("test.Foo", ""
        + "package test;\n"
        + "import com.google.auto.value.AutoValue;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonQualifier;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "@AutoValue public abstract class Foo<T, U> {\n"
        + "  public static <T, U>JsonAdapter<Foo<T, U>> jsonAdapter(Moshi moshi, "
        + "      Type[] types) {\n"
        + "    return null;"
        + "  }\n"
        + "  @FooPrefix public abstract T genericItem();\n"
        + "  public abstract List<T> listWithQualifier();\n"
        + "  public abstract String normalProperty();\n"
        + "  public abstract Map<T, U> map();\n"
        + "}"
    );

    JavaFileObject expected = JavaFileObjects.forSourceString("test/AutoValue_Foo", ""
        + "package test;\n"
        + "import com.squareup.moshi.JsonAdapter;\n"
        + "import com.squareup.moshi.JsonQualifier;\n"
        + "import com.squareup.moshi.JsonReader;\n"
        + "import com.squareup.moshi.JsonWriter;\n"
        + "import com.squareup.moshi.Moshi;\n"
        + "import com.squareup.moshi.Types;\n"
        + "import java.io.IOException;\n"
        + "import java.lang.NoSuchMethodException;\n"
        + "import java.lang.Override;\n"
        + "import java.lang.String;\n"
        + "import java.lang.annotation.Annotation;\n"
        + "import java.lang.reflect.Method;\n"
        + "import java.lang.reflect.ParameterizedType;\n"
        + "import java.lang.reflect.Type;\n"
        + "import java.lang.reflect.TypeVariable;\n"
        + "import java.util.LinkedHashSet;\n"
        + "import java.util.List;\n"
        + "import java.util.Map;\n"
        + "import java.util.Set;\n"
        + "final class AutoValue_Foo<T, U> extends $AutoValue_Foo<T, U> {\n"
        + "  AutoValue_Foo(T genericItem, List<T> listWithQualifier, String normalProperty, "
        + "    Map<T, U> map) {\n"
        + "    super(genericItem, listWithQualifier, normalProperty, map);\n"
        + "  }\n"
        + "  public static final class MoshiJsonAdapter<T, U> extends JsonAdapter<Foo<T, U>> {\n"
        + "    private static final String[] NAMES = new String[]\n"
        + "        {\"genericItem\",\"listWithQualifier\",\"normalProperty\", \"map\"};\n"
        + "    private static final JsonReader.Options OPTIONS = JsonReader.Options.of(NAMES);\n"
        + "    private final JsonAdapter<T> genericItemAdapter;\n"
        + "    private final JsonAdapter<List<T>> listWithQualifierAdapter;\n"
        + "    private final JsonAdapter<String> normalPropertyAdapter;\n"
        + "    private final JsonAdapter<Map<T, U>> mapAdapter;\n"
        + "    public MoshiJsonAdapter(Moshi moshi, Type[] types) {\n"
        + "      this.genericItemAdapter = adapterWithQualifier(moshi, \"genericItem\", "
        + "          types[0]);\n"
        + "      this.listWithQualifierAdapter = adapter(moshi, "
        + "          Types.newParameterizedType(List.class, types[0]));\n"
        + "      this.normalPropertyAdapter = adapter(moshi, String.class);\n"
        + "      this.mapAdapter = adapter(moshi, "
        + "          Types.newParameterizedType(Map.class, types[0], types[1]));\n"
        + "    }\n"
        + "    @Override\n"
        + "    public Foo<T, U> fromJson(JsonReader reader) throws IOException {\n"
        + "      reader.beginObject();\n"
        + "      T genericItem = null;\n"
        + "      List<T> listWithQualifier = null;\n"
        + "      String normalProperty = null;\n"
        + "      Map<T, U> map = null;\n"
        + "      while (reader.hasNext()) {\n"
        + "        switch (reader.selectName(OPTIONS)) {\n"
        + "          case 0: {\n"
        + "            genericItem = this.genericItemAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 1: {\n"
        + "            listWithQualifier = this.listWithQualifierAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 2: {\n"
        + "            normalProperty = this.normalPropertyAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case 3: {\n"
        + "            map = this.mapAdapter.fromJson(reader);\n"
        + "            break;\n"
        + "          }\n"
        + "          case -1: {\n"
        + "            // Unknown name, skip it\n"
        + "            reader.nextName();\n"
        + "            reader.skipValue();\n"
        + "          }\n"
        + "        }\n"
        + "      }\n"
        + "      reader.endObject();\n"
        + "      return new AutoValue_Foo(genericItem, listWithQualifier, normalProperty, map);\n"
        + "    }\n"
        + "    @Override\n"
        + "    public void toJson(JsonWriter writer, Foo<T, U> value) throws IOException {\n"
        + "      writer.beginObject();\n"
        + "      writer.name(\"genericItem\");\n"
        + "      this.genericItemAdapter.toJson(writer, value.genericItem());\n"
        + "      writer.name(\"listWithQualifier\");\n"
        + "      this.listWithQualifierAdapter.toJson(writer, value.listWithQualifier());\n"
        + "      writer.name(\"normalProperty\");\n"
        + "      this.normalPropertyAdapter.toJson(writer, value.normalProperty());\n"
        + "      writer.name(\"map\");\n"
        + "      this.mapAdapter.toJson(writer, value.map());\n"
        + "      writer.endObject();\n"
        + "    }\n"
        + "    private JsonAdapter adapter(Moshi moshi, Type adapterType) {\n"
        + "      return moshi.adapter(adapterType);\n"
        + "    }\n"
        + "    private JsonAdapter adapterWithQualifier(Moshi moshi, String methodName,\n"
        + "        Type declaredGenericType) {\n"
        + "      try {\n"
        + "        Method method = Foo.class.getMethod(methodName);\n"
        + "        Set<Annotation> annotations = new LinkedHashSet<>();\n"
        + "        for (Annotation annotation : method.getAnnotations()) {\n"
        + "          if (annotation.annotationType().isAnnotationPresent(JsonQualifier.class)) {\n"
        + "            annotations.add(annotation);\n"
        + "          }\n"
        + "        }\n"
        + "        Type adapterType = method.getGenericReturnType();\n"
        + "        if (declaredGenericType != null) {\n"
        + "          if (adapterType instanceof ParameterizedType) {\n"
        + "            adapterType = Types.newParameterizedType(\n"
        + "                ((ParameterizedType) adapterType).getRawType(), declaredGenericType);\n"
        + "          }\n"
        + "          else if (adapterType instanceof TypeVariable) {\n"
        + "            adapterType = declaredGenericType;\n"
        + "          }\n"
        + "        }\n"
        + "        return moshi.adapter(adapterType, annotations);\n"
        + "      } catch (NoSuchMethodException e) {\n"
        + "        throw new RuntimeException(\"No method named \" + methodName, e);\n"
        + "      }\n"
        + "    }\n"
        + "  }\n"
        + "}\n"
    );

    assertAbout(javaSources())
        .that(Arrays.asList(annotation, adapter, source))
        .processedWith(new AutoValueProcessor())
        .compilesWithoutError()
        .and().generatesSources(expected);
  }
}
